### ISSUE TITLE
IDena Verification Bug

### ISSUE THREAD

**Issue by digitalmnt** [gitcoinco/passport#2000]
A decent number of unhandled errors are being thrown from the Idena signin process. 

Here is a sample of the errors being thrown when you do not qualify for a stamp. 

```
{
		"code": 403,
		"error": "There was an unexpected error during verification. TypeError: Cannot read properties of undefined (reading 'state') at /usr/src/platforms/dist/commonjs/Idena/procedures/idenaSignIn.js:77:56"
	},
	{
		"code": 403,
		"error": "There was an unexpected error during verification. TypeError: Cannot read properties of undefined (reading 'state') at /usr/src/platforms/dist/commonjs/Idena/procedures/idenaSignIn.js:77:56"
	},
	{
		"code": 403,
		"error": "There was an unexpected error during verification. TypeError: Cannot read properties of undefined (reading 'state') at /usr/src/platforms/dist/commonjs/Idena/procedures/idenaSignIn.js:77:56"
	},
```
The linked PR should resolve this.

**Comment by digitalmnt** [comment]
Just waiting review

**Comment by digitalmnt** [comment]
I also manually disabled the alarm until this patch can be released. The alarm should be re-enabled on the next deployment
