### ISSUE TITLE
Improve error handling to detect failures like: "Signature does not belong to issuer", and advise user to refresh browser page or change wallet.

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#600]

**Comment by IlyaLoshchinin** [comment]
Hello everyone. I'm constantly getting the same error again and again. Refreshing or reloading the page/browser doesn't work for me. How to pass this error? I'd like to participate in Gitcoin Grants. 
A stack trace is below:

> ceramic.passport-iam.gitcoin.co/api/v0/commits:1          
> Failed to load resource: the server responded with a status of 500 ()
>
> _app-b008675a1017f9ba.js:1 Uncaught (in promise) Error: HTTP request to 'https://ceramic.passport-iam.gitcoin.co/api/v0/commits' failed with status '': {"error":"Can not verify signature for commit bagcqcerap5jhgia7cbrroxx4q73vjczoimgdp6dt27cqcd63efdpfymh7hkq: Signature does not belong to issuer"}
    at S (_app-b008675a1017f9ba.js:1:1763823)
    at async k.applyCommit (_app-b008675a1017f9ba.js:1:1764844)
    at async et.applyCommit (_app-b008675a1017f9ba.js:1:1773865)
    at async n.update (_app-b008675a1017f9ba.js:1:1780494)
    at async y.update (_app-b008675a1017f9ba.js:1:1801131)
    at async M._setRecordOnly (_app-b008675a1017f9ba.js:1:1798365)
    at async M.setRecord (_app-b008675a1017f9ba.js:1:1798082)
    at async M.merge (_app-b008675a1017f9ba.js:1:1795569)`

**Comment by nutrina** [comment]
@IlyaLoshchinin  please note, that we have pushed a fix for this. See here: https://discord.com/channels/562828676480237578/986222591096279040/1022028708908896297

**Comment by IlyaLoshchinin** [comment]
@nutrina nice, but not anyone has access to the private channel on discord. Please, write the info here. Thank you.

**Comment by nutrina** [comment]
@IlyaLoshchinin 
We have pushed a fix for the error that have been encountered with the passport app in the last 1-2 days. This should fix the "Ceramic Network Error" that some users are seeing or issues when saving stamps.
However, in order for this to work, users should:
1. clear the browser cache & cookies for at least the last 24 hours ( https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop )
2. refresh the browser page and try again
